// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import MapController from "./map_controller";
application.register("map", MapController);

import ToggleFavoriteController from "./toggle_favorite_controller";
application.register("toggle-favorite", ToggleFavoriteController);

import TomSelectController from "./tom_select_controller";
application.register("tom-select", TomSelectController);

// import 'bootstrap';
